#!/usr/bin/env sh

ScrDir=$(dirname "$(realpath "$0")")
source $ScrDir/globalcontrol.sh

hyprctl devices -j | jq -r '.keyboards[].name' | while read keyName; do
	hyprctl switchxkblayout "$keyName" us
	hyprctl switchxkblayout "$keyName" es_co
done

layMain=$(hyprctl -j devices | jq '.keyboards' | jq '.[] | select (.main == true)' | awk -F '"' '{if ($2=="active_keymap") print $4}')
notify-send -a "t1" -r 91190 -t 800 -i "~/.config/dunst/icons/keyboard.svg" "${layMain}"




Keyboards:
	Keyboard at 58f60bcc5b70:
		power-button
			rules: r "", m "", l "us", v "", o ""
			active keymap: English (US)
			main: no
	Keyboard at 58f60bc9fba0:
		power-button-1
			rules: r "", m "", l "us", v "", o ""
			active keymap: English (US)
			main: no
	Keyboard at 58f60c15c420:
		sino-wealth-wired-gaming-keyboard
			rules: r "", m "", l "us", v "", o ""
			active keymap: English (US)
			main: no
	Keyboard at 58f60c1b3890:
		sino-wealth-wired-gaming-keyboard-system-control
			rules: r "", m "", l "us", v "", o ""
			active keymap: English (US)
			main: no
	Keyboard at 58f60c2375a0:
		sino-wealth-wired-gaming-keyboard-consumer-control
			rules: r "", m "", l "us", v "", o ""
			active keymap: English (US)
			main: no
	Keyboard at 58f60c288140:
		sino-wealth-wired-gaming-keyboard-1
			rules: r "", m "", l "us", v "", o ""
			active keymap: English (US)
			main: yes
